openapi: 3.0.1
info:
  title: Ping-2         # ← zmień, jeśli „Ping” już był
  version: "0.0.2"
servers:
  - url: https://sklep621938.shoparena.pl/webapi/rest
paths:
  /auth:                      # istniejący w Twoim API
    post:
      operationId: auth
      summary: Token
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: { type: object }
